spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      hibernate:
        type: trace
